# Generated by Django 2.2.6 on 2019-10-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionsapp', '0003_auto_20191019_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'managed': True, 'verbose_name': 'LGA', 'verbose_name_plural': 'LGAs'},
        ),
        migrations.AlterModelOptions(
            name='senatorialdistrict',
            options={'managed': True, 'verbose_name': 'Senatorial District', 'verbose_name_plural': 'Senatorial Districts'},
        ),
    ]
