# Generated by Django 2.2.6 on 2019-10-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionsapp', '0004_auto_20191019_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senatorialdistrict',
            options={'managed': True, 'ordering': ['senatorial_district_name'], 'verbose_name': 'Senatorial District', 'verbose_name_plural': 'Senatorial Districts'},
        ),
    ]
